server:
  http_listen_port: 9080

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: rustraptor
    static_configs:
      - targets: [localhost]
        labels:
          job: rust-api
          __path__: /var/log/rustraptor/*.log
    pipeline_stages:
      - json
      - labels:
          level:
          target:
          file:           # our “path” field from tracing
