global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "rustraptor-backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["rust-backend:9000"]

  - job_name: "promtail"
    static_configs:
      - targets: ["promtail:9080"]
