name: Rust CI

on:
  push:
    branches: [master]            # run on direct pushes
  pull_request:
    branches: [master]            # and on PRs targeting master

# cancel previous CI run on the same branch / PR
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      # ── checkout repo ──────────────────────────────────────────
      - uses: actions/checkout@v4

      # ── Rust toolchain + components ────────────────────────────
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          override: true

      # ── cache Cargo registry / git / target ────────────────────
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      # ── formatting check ───────────────────────────────────────
      - name: rustfmt
        run: cargo fmt --check

      # ── static lints (deny warnings) ───────────────────────────
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      # ── full test suite ────────────────────────────────────────
      - name: tests
        run: cargo test --all-features --verbose
